// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyrmjcztuwcnulkwjscl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95cm1qY3p0dXdjbnVsa3dqc2NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUyMjUzNjEsImV4cCI6MjA5MDgwMTM2MX0.kuh6KpgDmt9LavxiI3EeQ0T3Cm1UXcYZFhDlQfJyPrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    ...(typeof window !== 'undefined' ? { storage: localStorage } : {}),
    persistSession: typeof window !== 'undefined',
    autoRefreshToken: true,
  }
});